name: Test

on:
  push:
    branches:
      - master
      - main
      - release-v*
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('packages/contracts/package-lock.json') }}
          restore-keys: npm-v2-
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run lint --workspace @rankanizer-contracts/contracts
      - run: npm run test --workspace @rankanizer-contracts/contracts
      - run: npm run test:inheritance --workspace @rankanizer-contracts/contracts
        env:
          FORCE_COLOR: 1
          ENABLE_GAS_REPORT: true
          CI: true
      - run: npm run gas-report --workspace @rankanizer-contracts/contracts
      - name: Print gas report
        run: cat ./packages/contracts/gas-report.txt

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('packages/contracts/package-lock.json') }}
          restore-keys: npm-v2-
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run coverage --workspace @rankanizer-contracts/contracts
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - uses: codecov/codecov-action@v2
